from clovai_apps.catalog import (
    APPS_CATALOG,
    CATALOG_APP_IDS,
    CATALOG_ID_BY_SLUG,
    VISIBLE_APP_SLUGS,
    CatalogAppSummary,
    find_app_by_id_or_slug,
    get_catalog_id_for_slug,
    is_known_app_slug,
    is_launch_app_slug,
    list_apps,
    list_visible_apps,
)
from clovai_apps.constants import (
    APP_SLUG_ALIASES,
    APP_SLUG_ASSET_REMIX,
    APP_SLUG_CAREER_COACH,
    APP_SLUG_CLOVAI_PROJECTS,
    APP_SLUG_CREATIVE_EDITOR,
    APP_SLUG_LOGO_STUDIO,
    APP_SLUG_PHOTO_GENERATOR,
    APP_SLUG_PHOTO_STUDIO,
    APP_SLUG_RESEARCH_COMPANION,
    APP_SLUG_VIDEO_SNIPPETS,
    APP_SLUG_VOICE_MAKER,
    LAUNCH_APP_SLUGS,
    normalize_app_slug,
)
from clovai_apps.photo_studio.schemas import (
    PhotoStudioGenerateRequest,
    PhotoStudioGenerateResponse,
    PhotoStudioGeneratedItem,
    PhotoStudioOptionsResponse,
)
from clovai_apps.photo_studio.service import generate_photo_studio_variants, get_photo_studio_options
from clovai_apps.shared.assets import (
    ASSET_KIND_METADATA_KEY,
    IMAGE_EXTENSIONS,
    IMAGE_MIME_TYPES,
    PHOTO_STUDIO_REFERENCE_METADATA_KEY,
    build_image_document_metadata,
    default_image_filename,
    detect_upload_kind,
    is_image_upload,
)

__all__ = [
    "APP_SLUG_ALIASES",
    "APP_SLUG_ASSET_REMIX",
    "APP_SLUG_CAREER_COACH",
    "APP_SLUG_CLOVAI_PROJECTS",
    "APP_SLUG_CREATIVE_EDITOR",
    "APP_SLUG_LOGO_STUDIO",
    "APP_SLUG_PHOTO_GENERATOR",
    "APP_SLUG_PHOTO_STUDIO",
    "APP_SLUG_RESEARCH_COMPANION",
    "APP_SLUG_VIDEO_SNIPPETS",
    "APP_SLUG_VOICE_MAKER",
    "APPS_CATALOG",
    "ASSET_KIND_METADATA_KEY",
    "CATALOG_APP_IDS",
    "CATALOG_ID_BY_SLUG",
    "IMAGE_EXTENSIONS",
    "IMAGE_MIME_TYPES",
    "LAUNCH_APP_SLUGS",
    "PHOTO_STUDIO_REFERENCE_METADATA_KEY",
    "VISIBLE_APP_SLUGS",
    "CatalogAppSummary",
    "PhotoStudioGenerateRequest",
    "PhotoStudioGenerateResponse",
    "PhotoStudioGeneratedItem",
    "PhotoStudioOptionsResponse",
    "build_image_document_metadata",
    "default_image_filename",
    "detect_upload_kind",
    "find_app_by_id_or_slug",
    "generate_photo_studio_variants",
    "get_catalog_id_for_slug",
    "get_photo_studio_options",
    "is_image_upload",
    "is_known_app_slug",
    "is_launch_app_slug",
    "list_apps",
    "list_visible_apps",
    "normalize_app_slug",
]

__version__ = "0.1.0"
